// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChallengeFeeback: typeof import('./src/components/challengeFeeback.vue')['default']
    ChallengeMask: typeof import('./src/components/challengeMask.vue')['default']
    ChallengeQuestion: typeof import('./src/components/challengeQuestion.vue')['default']
    ChallengeQuit: typeof import('./src/components/challengeQuit.vue')['default']
    ChallengeScroeBoard: typeof import('./src/components/challengeScroeBoard.vue')['default']
    LoadProgress: typeof import('./src/components/loadProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
  }
}
